fscrypt: Fix misleading indentation
fs/crypto/policy.c:656:4: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
  656 |                         return 0;
      |                         ^
fs/crypto/policy.c:654:3: note: previous statement is here
  654 |                 if (!strcmp(boot, SDHCI) && !strcmp(file_system_type, "f2fs"))
      |                 ^
1 error generated.

Change-Id: I14c5d8aec6ff611be24548dd228ee0264c72ab38
(cherry picked from commit 1f337f06c2eb07a02c1bb4ecb06c0e04fc848210)