usb_bam: Fix misleading indentations
drivers/platform/msm/usb_bam.c:1158:4: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]
 1158 |                         spin_unlock(&ctx->usb_bam_lock);
      |                         ^
drivers/platform/msm/usb_bam.c:1156:3: note: previous statement is here
 1156 |                 else
      |                 ^
drivers/platform/msm/usb_bam.c:1279:4: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]
 1279 |                         spin_unlock(&ctx->usb_bam_lock);
      |                         ^
drivers/platform/msm/usb_bam.c:1277:3: note: previous statement is here
 1277 |                 else
      |                 ^
2 errors generated.

Change-Id: Iff4ccebdbb25d8294f74ebdb7f9053a5f6b1da85
(cherry picked from commit c4d84c574de626a0e2c17593eb1473465b56798c)